### PR TITLE
Adds loads on content in raw envelope

### PR DESCRIPTION
**Pull request by wheremiah**
@jessemyers  - Is this correct or should be create our own strategy

### CODE REVIEW

**Comment by jessemyers** [comment]
It seems correct, but unit tests are failing?

**Comment by sethisernhagen** [comment]
I think we need to do dumps() here https://github.com/globality-corp/microcosm-pubsub/blob/develop/microcosm_pubsub/tests/test_envelope.py#L32

```
    sqs_message = envelope.parse_raw_message(consumer, dict(
        MessageId=message_id,
        ReceiptHandle=receipt_handle,
        Body=dumps(dict(
            foo="bar",
        )),
    ))
```

**Comment by wheremiah** [comment]
@sethisernhagen I think you are right, thx!

**Comment by jessemyers** [comment]
LGTM

**Pull request merged**
